pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/AryanThakur41/django-pipeline-.git'
            }
        }
        
        stage('SSH on Server') {
            steps {
                sshagent (credentials: ['ssh-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@54.205.201.56 "bash -s" < ./cool_counters/python.sh
                    '''
                }
            }
        }
        
       
        steps {
                sshagent (credentials: ['ssh-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@54.205.201.56 "bash -s" < ./cool_counters/deploy.sh
                    '''
                }
            }
    }
    
    post {
        success {
            echo 'Deployment was successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
