pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/AryanThakur41/django-pipeline-.git'
            }
        }
        
        stage('SSH on Server') {
            steps {
                sshagent (credentials: ['ssh-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@3.85.34.223 "bash -s" < ./cool_counters/python.sh
                    '''
                }
            }
        }
        
        stage('Install Python') {
            steps {
                sh '''
                chmod +x ./cool_counters/python.sh   
                ./cool_counters/python.sh
                '''
            }
        }
        
        stage('Deploy') {
            steps {
                sh '''
                chmod +x ./cool_counters/deploy.sh   
                ./cool_counters/deploy.sh
                '''
            }
        }
    }
    
    post {
        success {
            echo 'Deployment was successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
